# use --project=pebble-notes for gcloud
runtime: python310
# api_version: 1
# threadsafe: true
# app_engine_apis: true
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  ENVIRONMENT: production
  SECRET_KEY: 

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /auth.*
  script: auth.application

- url: /
  static_dir: static
