runtime: python310
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b :$PORT main:app

env_variables:
  ENVIRONMENT: production

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /auth.*
  script: auto

- url: /
  static_dir: static