runtime: python310
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4

env_variables:
  ENVIRONMENT: production

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /auth.*
  script: auto

- url: /
  static_dir: static