on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Pebble app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Create build directories
        run: mkdir -p build/{aplite,basalt,chalk,diorite,js,src,c4che,emery,include}
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: bboehmke/pebble-dev:latest
          options: --user root -v ${{ github.workspace }}:/pebble/ 
          run: |
            npm install -g jshint uglify-js
            echo $PATH
            which jshint
            which uglifyjs
            pebble build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pebble Notes PBW
          path: |
            build/PebbleNotes.pbw
