on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Pebble app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ngencokamin/pebble-dev
          options: --user root --rm -v ${{ github.workspace }}:/pebble/ 
          run: |
            npm i -g jshint uglify-js
            echo $PATH
            which jshint
            which uglifyjs
            yes | pebble build
            mv build/pebble.pbw build/PebbleNotes.pbw
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pebble Notes PBW
          path: |
            build/PebbleNotes.pbw
